S11share: 2 parts upgrade - install /boot then reboot - install / then reboot

diff --git a/board/recalbox/fsoverlay/etc/init.d/S11share b/board/recalbox/fsoverlay/etc/init.d/S11share
--- a/board/recalbox/fsoverlay/etc/init.d/S11share
+++ b/board/recalbox/fsoverlay/etc/init.d/S11share
@@ -24,6 +24,9 @@ NTRY=0
 # let's keep a marge to have a value always under 100% (that's just for the percentage)
 NB_FILES_TARGET=45000
 
+# A flag for to tell /boot was upgraded successfully
+UPDBOOTFLAG="/boot/boot.upgraded"
+
 ##### BUT FIRST, create the internal partition if it doesn't exist
 # command that can be used for test to remove the 3rd partition : parted -s -m /dev/mmcblk0 rm 3
 # create the internal partition if it doesn't exist
@@ -103,7 +106,7 @@ scr_msg_upgrade() {
 do_upgrade() {
     BOOTTAR="/recalbox/share/system/upgrade/boot.tar.xz"
     ROOTTAR="/recalbox/share/system/upgrade/root.tar.xz"
-
+    
     # percentage
     touch /tmp/upgrade.files
     (
@@ -123,19 +126,26 @@ do_upgrade() {
     echo "Upgrading /boot"
     if mount -o remount,rw /boot
     then
-	if (cd /boot && \
+	if [ ! -f "${UPDBOOTFLAG}" ] && (cd /boot && \
 	    cp cmdline.txt cmdline.txt.upgrade && \
 	    cp config.txt config.txt.upgrade && \
 	    cp recalbox-boot.conf recalbox-boot.conf.upgrade && \
 	    xz -dc < "${BOOTTAR}" | tar xvf - >> /tmp/upgrade.files && \
 	    mv recalbox-boot.conf.upgrade recalbox-boot.conf && \
 	    mv config.txt.upgrade config.txt && \
-	    mv cmdline.txt.upgrade cmdline.txt )
+	    mv cmdline.txt.upgrade cmdline.txt && \
+        touch "${UPDBOOTFLAG}")
 	then
-	    EXIT_CODE=0
+	    EXIT_CODE=2
+    elif [ -f "${UPDBOOTFLAG}" ]; then
+        # return code can't be 1 (/boot updated) or 1 (failed) but 
+        # a 3rd value (/boot previously updated) and we keep on updating
+        echo "/boot has been upgraded. $UPDBOOTFLAG created !"
+        EXIT_CODE=3
 	fi
 	sync
     fi
+    test "${EXIT_CODE}" = 2 && return 2 # /boot updated successfully, let ir reboot
     test "${EXIT_CODE}" = 1 && return 1 # don't insist if /boot failed to upgrade
 
     date
@@ -146,16 +156,19 @@ do_upgrade() {
     echo "Upgrading /"
     if mount -o remount,rw /
     then
-	if (cd / && \
+	if [ -f "${UPDBOOTFLAG}" ] && (cd / && \
 	    cp ./etc/fstab ./etc/fstab.upgrade && \
             rm -rf /usr/share/lirc/contrib/lircrc && \
 	    xz -dc < "${ROOTTAR}" | tar xvf - >> /tmp/upgrade.files && \
 	    mv ./etc/fstab.upgrade ./etc/fstab)
 	then
-	    EXIT_CODE=0
+	    echo "root successfully untarred, removing $UPDBOOTFLAG"
+        # /boot should already be RW here
+        mount -o remount,rw /boot && rm ${UPDBOOTFLAG} && EXIT_CODE=0
 	fi
 	sync
     fi
+    
     test "${EXIT_CODE}" = 1 && return 1 # don't insist if /root failed to upgrade
 
     echo "Upgrade ended successfully."
@@ -216,10 +229,15 @@ if test -e "/recalbox/share/system/upgrade/boot.tar.xz" -a -e "/recalbox/share/s
 then
     # let's go
     scr_init_upgrade
+    # remove previous logs BUT logs of the previous reboot if /boot only was updated
+    [ ! -f /boot/boot.upgraded ] && rm /recalbox/share/system/upgrade/update*log*
+    # rename logs to keep the history of the /boot upgrade
+    for file in $(ls /recalbox/share/system/upgrade/upgrade.*.log) ; do mv "$file" "$file".prereboot ; done
     do_upgrade > /recalbox/share/system/upgrade/upgrade.out.log 2> /recalbox/share/system/upgrade/upgrade.err.log
-    
-    # remove to not apply it indefinitly, even if it fails
-    rm "/recalbox/share/system/upgrade/boot.tar.xz" "/recalbox/share/system/upgrade/root.tar.xz"
+    if [ $? -eq "0" ]; then
+        # remove to not apply it indefinitly, even if it fails
+        rm "/recalbox/share/system/upgrade/boot.tar.xz" "/recalbox/share/system/upgrade/root.tar.xz"
+    fi
     
     # rebooting now
     shutdown -r now
